language: node_js

node_js:
  - '12.18.3'

cache: 
  yarn: true
  directories:
    - node_modules

branches:
  only: 
    - master

jobs: 
  include:
    - stage: 'building'
      script:
        - yarn install

    - stage: 'test'
      script:
        - yarn test